# Arguments:
ARG RUST_VERSION=1.72.0
ARG APP_NAME=texcollector

FROM rust:${RUST_VERSION}-slim-bullseye AS chef

ARG APP_NAME

# Cargo chef is used for caching dependencies:
RUN cargo install cargo-chef

WORKDIR /app

# Prepare cached recipe.json:
FROM chef AS planner
COPY . .
RUN cargo chef prepare  --recipe-path recipe.json

FROM chef AS builder
COPY --from=planner /app/recipe.json recipe.json
# Build dependencies - this is the caching Docker layer!
RUN cargo chef cook --release --recipe-path recipe.json

# Build application
COPY . .
RUN cargo build

# What the container should run when it is started.
CMD ["bash"]